### ISSUE TITLE
Set files enabled to True

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/galter_ir_exporter#25]
When exporting, `"files": {"enabled": true}` is missing from "record". Add it for all records:

```json
{
  "record": {
    "metadata": {...},
    "files": {
      "enabled": true
    },
    ...
}
```

Yes, we could add it on the import side, so low priority. The Idea is to have as many things as possible done by exporter though so that data is transferred as-is. To be frank, it's also a workload offset, so that I am freed up to do the import parts that can't be done in the exporter.

**Comment by Meowcenary** [comment]
Happy to handle it on the export side. Seems pretty simple to add, but I guess we'll see when it goes to review.
