### ISSUE TITLE
Update resource_types field

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/galter_ir_exporter#26]
The most up-to-date documentation can now be found here: https://inveniordm-qa.docs.cern.ch/reference/rest_api/ . This site updates whenever master of https://github.com/inveniosoftware/docs-invenio-rdm/ is updated. There is some caching so make sure to hard refresh if something looks strange.

Resource types should now look like:

```json
{
  "record": {
    "metadata": {
      "resource_type": {
        "id": "image-photo"
      },
      ...
    }
  }
}
```
The resource types id should be picked from to-be-pushed: resource_types.yaml in digitalhub-2 repository.

**Comment by sharpattack** [comment]
Dependent on /galterlibrary/digitalhub-2/issues/54

**Comment by fenekku** [comment]
closed via https://github.com/galterlibrary/digital-repository/pull/884
