### ISSUE TITLE
Update exported languages

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/galter_ir_exporter#27]
Exported languages should follow this structure:

```json
{
  "record": {
    "metadata": {
      "languages": [
        {
          "id": "aaa"
        },
        ...
      ],
      ...
    }
  }
}
```

And take their `id`s from https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/languages.yaml . The official documentation needs to be updated.

**Comment by sharpattack** [comment]
Can we have multiple? i.e.
```
{
  "record": {
    "metadata": {
      "languages": [
        {
          "id": "aaa",
          "id": "bbb"
        },
        ...
      ],
      ...
    }
  }
}

**Comment by fenekku** [comment]
No if there is no language then the strcuture should be:

```json
{
  "record": {
    "metadata": {
      "languages": [],
      ...
    }
  }
}
```

**Comment by fenekku** [comment]
skipping languages entirely is also possible:

```json
{
  "record": {
    "metadata": {
            ...
    }
  }
}
```

i.e. no `"languages"` key

**Comment by Meowcenary** [comment]
I'm going to plan on using an empty array for no languages.
