### ISSUE TITLE
Update exported role

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/galter_ir_exporter#28]
The "role" field should have the following structure:

```json
{
  "record": {
    "metadata": {
      "creators": [
        {
          "person_or_org": {...},
          "role": {"id": "<id of role>"},  # optional for creators
          "affiliations": {...}
        },
        ...
      ],
      "contributors": [
        {
          "person_or_org": {...},
          "role": {"id": "<id of role>"},
          "affiliations": {...}
        },
        ...
      ],
      ...
    }
  }
}
```

This new structure will be supported after the June release, so the official list of potential `id`s is not finalized yet. The placement of role at the same level as `"person_or_org"` is the case now though.

**EDIT 2021-06-28**
- The box file of supported roles that librarians have created for Prism: https://northwestern.app.box.com/file/725826115682?s=zw0qwyb119x2habxg4b17ija65lf2i1i
- Its translation into a developer file with id per role in digitalhub-2: https://github.com/galterlibrary/digitalhub-2/blob/master/app_data/vocabularies/roles.yaml
- There is no established correspondances between DH and Prism in terms of roles as per: https://northwestern.app.box.com/file/684887467855?s=1e1ogwnz4vrh7upmrlfuf3nk4vw1ap64

**Comment by Meowcenary** [comment]
haha. I had a breaking spec that made me realize we will need to delete the memoized information for these fields. I think the only file is `memoized_person_or_org_data.txt`, but I'll comment back if I find another.

**Comment by Meowcenary** [comment]
We've decide that we will omit the role filed from creators, but for the contributors we will assign them all the role "Other Role".  I'm going to email Katie and Liping now to see if they have any thoughts on the dates in some of the names, but unless they say otherwise I'll plan on keeping the full text from that field.
